language: generic

os:
  - linux
  - osx

env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
    - SDL2=SDL2-2.0.4
    - SDL2_TTF=SDL2_ttf-2.0.12

cache:
  directories:
    - $HOME/.stack
    - $HOME/$SDL2
    - $HOME/$SDL2_TTF

addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      if [[ ! -d "$SDL2" ]]; then
        wget http://libsdl.org/release/"$SDL2".tar.gz -O - | tar xz
        (cd "$SDL2" && ./configure && make -j)
      fi
      (cd "$SDL2" && sudo make install)
      if [[ ! -d "$SDL2_TTF" ]]; then
        wget http://libsdl.org/projects/SDL_ttf/release/"$SDL2_TTF".tar.gz -O - | tar xz
        (cd "$SDL2_TTF" && ./configure && make -j)
      fi
      (cd "$SDL2_TTF" && sudo make install)
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      mkdir -p ~/.local/bin
      export PATH=$HOME/.local/bin:$PATH
      travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz \
        | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew install haskell-stack pkg-config sdl2 sdl2_ttf
    fi

install:
  - stack --no-terminal --install-ghc build --only-dependencies

script:
  - stack --no-terminal build
