language: generic

os:
  - linux
  - osx

env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
    - SDL2=SDL2-2.0.4
    - SDL2_TTF=SDL2_ttf-2.0.12

cache:
  directories:
    - $HOME/.stack
    - $HOME/$SDL2
    - $HOME/$SDL2_TTF

addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      if [[ ! -d "$SDL2" ]]; then
        wget http://libsdl.org/release/"$SDL2".tar.gz -O - | tar xz
        (cd "$SDL2" && ./configure && make -j)
      fi
      (cd "$SDL2" && sudo make install)
      if [[ ! -d "$SDL2_TTF" ]]; then
        wget http://libsdl.org/projects/SDL_ttf/release/"$SDL2_TTF".tar.gz -O - | tar xz
        (cd "$SDL2_TTF" && ./configure && make -j)
      fi
      (cd "$SDL2_TTF" && sudo make install)
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      mkdir -p ~/.local/bin
      export PATH=$HOME/.local/bin:$PATH
      travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz \
        | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew install haskell-stack pkg-config sdl2 sdl2_ttf
    fi

install:
  - stack --no-terminal --install-ghc build --only-dependencies

script:
  - stack --no-terminal build

before_deploy:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      bash bundle/osx.sh
      export DEPLOY_FILE=space-osx.zip
    fi

deploy:
  provider: releases
  api_key:
    secure: JAx1hyjJu3Pn1AyRDQbaVpg6BQ08dPIonbUJP96Og+XSKhu2hIfkqSlke0yfXqpj+rcNrtpEakffaHcWbsHrebhR7B9Scihr0NCnhCe4z7aozih+OUvgpLeBvD640jahkKkEthQikI4OHB6ZGnGQmDNP8BK8ZwQw5+18JFGTrbUMk0SmxO/fKUown9WFsFiLyUZ03Zy9Mj+bMGJDCzYViJebrnCvBaTDMG03j4rJMir6kDbbCWPCE9/+ki4Jv3hb5RFo+FazSek/3+/+MZXnnwZH/ZPDpIoxlfe46s9Vd2rJlHRG3nrNBuAEeqxHchWV51yk1MyegNnkeXwf1ik6c6sz5Xx0Hhx86XioE+U4kgVllOaFD9mKoJGQwcIqNWnF+ulEB31zmYvs00OnEheCyBMURPxDryo7/KkwVb1VGCD98vJ7zjg+lEj04jJuM9wscerVpRw3EmO5f+0xJj8hLp5BkoAgYubZ4YHRaNiAFzqTWi7C0DMxsPaqlu3VQHKYPSilkAVSFW7s7S98plc9t8llXdqPAktceYxG59wVkcv/J89HD104Qmw1SpmVrnHncmnN6ezFd8j/cxlWop3NnGmccvzbkUkIwHJ9kEeL3eJYJA9j7z0np9dBFzqPV+7d00bUZ+2pgZMRC3aq84T7Obt4CW1MHTGi8DiR09AlhZs=
  file: $DEPLOY_FILE
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = osx
